version: '3.7'
services:
  backend:
    container_name: backend_provider
    image: ghcr.io/dormlife-softeng/backend-image:0.1-prod
    depends_on:
      - db
    ports:
      - 5000:3000
    command: npm run start:prod

  db:
    container_name: mongol
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:

