version: '3.3'
services:
  backend:
    container_name: backend_provider
    image: ghcr.io/dormlife-softeng/backend-image:latest-dev
    depends_on:
      - db
    ports:
      - 5000:3000
    command: npm run start:prod

  frontend:
   container_name: frontend_provider
   image: ghcr.io/dormlife-softeng/frontend:latest-prod
   depends_on:
     - db
     - backend
   ports:
     - 80:80
   stdin_open: true
   tty: true
  db:
    container_name: mongol
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:

